CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_app_user_public_id UNIQUE (public_id)
);

CREATE TABLE match_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    outcome VARCHAR(20),
    player_wins INT NOT NULL,
    computer_wins INT NOT NULL,
    current_round_number INT NOT NULL,
    summary_message VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL,
    CONSTRAINT uk_match_record_public_id UNIQUE (public_id),
    CONSTRAINT fk_match_record_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE TABLE match_round (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    round_number INT NOT NULL,
    player_move VARCHAR(10) NOT NULL,
    computer_move VARCHAR(10) NOT NULL,
    result VARCHAR(10) NOT NULL,
    message VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_match_round_match FOREIGN KEY (match_id) REFERENCES match_record (id),
    CONSTRAINT uk_match_round_number UNIQUE (match_id, round_number)
);

CREATE INDEX idx_match_record_user_created_at ON match_record (user_id, created_at DESC);
CREATE INDEX idx_match_record_status ON match_record (status);
CREATE INDEX idx_match_round_match_id ON match_round (match_id);