# Generated by Django 5.2.1 on 2026-03-30 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('PLAYER', 'Player Won'), ('COMPUTER', 'Computer Won'), ('TIE', 'Tie'), ('ABANDONED', 'Abandoned')], max_length=20, null=True)),
                ('player_score', models.PositiveSmallIntegerField(default=0)),
                ('computer_score', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='game.player')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('player_move', models.CharField(choices=[('ROCK', 'Rock'), ('PAPER', 'Paper'), ('SCISSORS', 'Scissors')], max_length=20)),
                ('computer_move', models.CharField(choices=[('ROCK', 'Rock'), ('PAPER', 'Paper'), ('SCISSORS', 'Scissors')], max_length=20)),
                ('outcome', models.CharField(choices=[('PLAYER', 'Player Won'), ('COMPUTER', 'Computer Won'), ('TIE', 'Tie')], max_length=20)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.match')),
            ],
            options={
                'ordering': ['round_number'],
                'constraints': [models.UniqueConstraint(fields=('match', 'round_number'), name='unique_round_per_match')],
            },
        ),
    ]
